-- Изменение функции триггера
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Таблица users
ALTER TABLE users 
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN created_at SET DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  ALTER COLUMN last_login TYPE BIGINT USING EXTRACT(EPOCH FROM last_login)::BIGINT;

-- Таблица posts
ALTER TABLE posts 
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN created_at SET DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  ALTER COLUMN updated_at DROP DEFAULT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT,
  ALTER COLUMN updated_at SET DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT;

-- Таблица comments
ALTER TABLE comments 
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN created_at SET DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  ALTER COLUMN updated_at DROP DEFAULT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT,
  ALTER COLUMN updated_at SET DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT;
